LDLIBS=-ldb -lcrypto
LDFLAGS=-L/usr/local/lib/db46
CFLAGS=-DMCCME=1 -I/usr/local/include/db46


OBJ=actions.o user.o eventdb.o dbs.o

eventdb: ${OBJ}
	${CC} ${LDFLAGS} ${OBJ} ${LDLIBS} -o $@

clean:
	rm -f -- *.o eventdb
