LDLIBS=-ldb -lcrypto
LDFLAGS=-L/usr/local/lib/db46
CFLAGS=-DMCCME=1 -I/usr/local/include/db46


OBJ=dbs.o user.o event.o log.o actions.o eventdb.o

eventdb: ${OBJ}
	${CC} ${LDFLAGS} ${OBJ} ${LDLIBS} -o $@

clean:
	rm -f -- *.o eventdb
